version: "3.9"

services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=username
      - POSTGRES_DB=flask_react
    ports:
      - "5432:5432"
    volumes:
      - ./data/raw-data:/raw-data
      - ./data/sql/tables.sql:/docker-entrypoint-initdb.d/1-tables.sql
      - ./data/sql/import.sql:/docker-entrypoint-initdb.d/2-import.sql
