version: "3.9"

services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=username
      - POSTGRES_DB=flask_react
    ports:
      - "5432:5432"
    volumes:
      - ./data/raw-data:/raw-data
      - ./data/sql/tables.sql:/docker-entrypoint-initdb.d/1-tables.sql
      - ./data/sql/import.sql:/docker-entrypoint-initdb.d/2-import.sql

  flask_datastore:
    build:
      context: flask-datastore
      dockerfile: docker/Dockerfile
    depends_on:
      - postgres
    environment:
      - POSTGRES_HOST=postgres
    container_name: flask-datastore
    ports:
      - "5001:5001"

  flask_backend:
    build:
      context: flask-backend
      dockerfile: docker/Dockerfile
    depends_on:
      - flask_datastore
    environment:
      - DATASTORE_HOST=flask_datastore
    container_name: flask-backend
    ports:
      - "5002:5002"


networks:
  default:
    driver: bridge